AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  RiotintoCleanerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 10
      MemorySize: 128

